dsn: mysql://ken:123@(192.168.199.128:3307)/kratos?parseTime=true&multiStatements=true

serve:
  public:
    host: 0.0.0.0
    port: 4433
    #告诉 Kratos自己:你现在跑在 http://192.168.199.128:4433,以后生成所有回调URL的时候就基于这个来搞
    base_url: http://192.168.199.128:4433
  admin:
    host: 0.0.0.0
    port: 4434

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/kratos/identity.schema.json

selfservice:
  #当用户注册/登录/验证 完成之后,如果 flow 里没指定 redirect_to,就跳转到这个地址
  default_browser_return_url: http://192.168.199.128:3000/dashboard
  methods:
    password:
      enabled: true
    oidc:
      enabled: true
  #当浏览器访问Kratos的flow接口,比如/self-service/registration/browser,Kratos处理完后,告诉浏览器跳转到前端UI的对应页面
  flows:
    registration:
      ui_url: http://192.168.199.128:3000/registration
    login:
      ui_url: http://192.168.199.128:3000/login
    settings:
      ui_url: http://192.168.199.128:3000/settings
    recovery:
      ui_url: http://192.168.199.128:3000/recovery
    verification:
      ui_url: http://192.168.199.128:3000/verification

secrets:
  cookie:
    - "16-or-more-char-secret"
  cipher:
    - "32-char-long-secret-key-here-123"

session:
  lifespan: 1h

log:
  level: debug